# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(582, 446)
        Form.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(40, 70, 231, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.groupBox.setObjectName("groupBox")
        self.lbl_x = QtWidgets.QLabel(self.groupBox)
        self.lbl_x.setGeometry(QtCore.QRect(20, 40, 31, 22))
        self.lbl_x.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(191, 191, 191);")
        self.lbl_x.setObjectName("lbl_x")
        self.lbl_y = QtWidgets.QLabel(self.groupBox)
        self.lbl_y.setGeometry(QtCore.QRect(20, 80, 31, 22))
        self.lbl_y.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(191, 191, 191);")
        self.lbl_y.setObjectName("lbl_y")
        self.txt_y = QtWidgets.QTextEdit(self.groupBox)
        self.txt_y.setGeometry(QtCore.QRect(60, 80, 100, 22))
        self.txt_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_y.setObjectName("txt_y")
        self.txt_x = QtWidgets.QTextEdit(self.groupBox)
        self.txt_x.setGeometry(QtCore.QRect(60, 40, 100, 22))
        self.txt_x.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_x.setObjectName("txt_x")
        self.btn_1 = QtWidgets.QPushButton(self.groupBox)
        self.btn_1.setGeometry(QtCore.QRect(110, 120, 99, 30))
        self.btn_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.btn_1.setObjectName("btn_1")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 70, 231, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_2.setGeometry(QtCore.QRect(70, 70, 99, 30))
        self.btn_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.btn_2.setObjectName("btn_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 260, 231, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.txt_nombre = QtWidgets.QTextEdit(self.groupBox_3)
        self.txt_nombre.setGeometry(QtCore.QRect(30, 60, 181, 31))
        self.txt_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nombre.setObjectName("txt_nombre")
        self.btn_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_3.setGeometry(QtCore.QRect(110, 120, 99, 30))
        self.btn_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.btn_3.setObjectName("btn_3")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 260, 231, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_4.setGeometry(QtCore.QRect(50, 40, 141, 30))
        self.btn_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_5.setGeometry(QtCore.QRect(50, 80, 141, 30))
        self.btn_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_6.setGeometry(QtCore.QRect(50, 120, 141, 30))
        self.btn_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.btn_6.setObjectName("btn_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 10, 171, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "COORDENADAS"))
        self.lbl_x.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">X</span></p></body></html>"))
        self.lbl_y.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Y</span></p></body></html>"))
        self.txt_y.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PibotoLt\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.txt_x.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PibotoLt\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_1.setText(_translate("Form", "PULSAR"))
        self.groupBox_2.setTitle(_translate("Form", "AREA DE TRABAJO"))
        self.btn_2.setText(_translate("Form", "PULSAR"))
        self.groupBox_3.setTitle(_translate("Form", "NOMBRE"))
        self.txt_nombre.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PibotoLt\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_3.setText(_translate("Form", "PULSAR"))
        self.groupBox_4.setTitle(_translate("Form", "IMAGENES"))
        self.btn_4.setText(_translate("Form", "CHEVROLET"))
        self.btn_5.setText(_translate("Form", "HYUNDAI"))
        self.btn_6.setText(_translate("Form", "TESLA"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">ROBOT 2 DOF</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
